# Generated by Django 3.1.3 on 2020-12-07 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201207_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='name',
            new_name='product_name',
        ),
    ]
