# Generated by Django 3.1.3 on 2020-12-08 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20201208_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='start_price',
            new_name='starting_bid',
        ),
    ]
