# Generated by Django 3.1.3 on 2020-12-08 15:07

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20201208_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='start_price',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_price',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
